# -*- coding: utf-8 -*-
"""pruebademicel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHXxiwWrkZ2gpvSfehhvjUvCUZB-1v47
"""

class celular():
  wats = int(input("Wats del telefono: "))
  espacio = int(input("Espacio del telefono: "))
  ram = int(input("Ram del telefono: "))
  ancho = int(input("Ancho del telefono: "))
  largo = int(input("Largo del telefono: "))
  encendido = False

  def encendido(self):
    self.encendido = True

  def estado(self):
    if(self.encendido):
      return "Encendido"
    else:
      return "Apagado"



micelular = celular()
print("Los wats de mi telefono son de: ", micelular.wats)
print("El espacio de mi telefono es de: ", micelular.espacio, "gygabytes")
print("La ram de mi telefono es de: ", micelular.ram, "gygabytes")
print("El ancho de mi telefono es de: ", micelular.ancho, "centimetros")
print("El largo de mi telefono es de: ", micelular.largo, "centimetros")